### ISSUE TITLE
BLAST

### ISSUE THREAD

**Issue by maxscheel** [fsmg/mirror-requests#16]
Website: http://blast.ncbi.nlm.nih.gov
Details on becoming a mirror: ftp://ftp.ncbi.nih.gov/blast/db/README

ftp://ftp.ncbi.nih.gov/blast/db/

**Comment by gizmoguy** [comment]
Thanks for reaching out @maxscheel 

We aren't currently in the business of mirroring scientific data (not enough storage space unfortunately) but the good news is our infrastructure partners REANNZ are and it looks like you are REANNZ members.

I will send you an email to the one on your GitHub account to close the loop between you and REANNZ.
